#ifdef __dingens
rom const char  x0klein[25];
rom const char  y0klein[25];
rom const char  x1klein[15];
rom const char  y1klein[15];
rom const char  x2klein[20];
rom const char  y2klein[20];
rom const char  x3klein[19];
rom const char  y3klein[19];
rom const char  x4klein[20];
rom const char  y4klein[20];
rom const char  x5klein[22];
rom const char  y5klein[22];
rom const char  x6klein[23];
rom const char  y6klein[23];
rom const char  x7klein[17];
rom const char  y7klein[17];
rom const char  x8klein[23];
rom const char  y8klein[23];
rom const char  x9klein[23];
rom const char  y9klein[23];
rom const char  xa[22];
rom const char  ya[22];
rom const char  xaklein[20];
rom const char  yaklein[20];
rom const char  xaus[12];
rom const char  yaus[12];
rom const char  xb[26];
rom const char  yb[26];
rom const char  xbklein[21];
rom const char  ybklein[21];
rom const char  xc[19];
rom const char  yc[19];
rom const char  xcklein[17];
rom const char  ycklein[17];
rom const char  xd[24];
rom const char  yd[24];
rom const char  xdklein[21];
rom const char  ydklein[21];
rom const char  xe[21];
rom const char  ye[21];
rom const char  xeklein[19];
rom const char  yeklein[19];
rom const char  xf[18];
rom const char  yf[18];
rom const char  xfklein[15];
rom const char  yfklein[15];
rom const char  xfrag[16];
rom const char  yfrag[16];
rom const char  xg[23];
rom const char  yg[23];
rom const char  xgklein[23];
rom const char  ygklein[23];
rom const char  xh[23];
rom const char  yh[23];
rom const char  xhklein[18];
rom const char  yhklein[18];
rom const char  xi[17];
rom const char  yi[17];
rom const char  xiklein[11];
rom const char  yiklein[11];
rom const char  xj[17];
rom const char  yj[17];
rom const char  xjklein[12];
rom const char  yjklein[12];
rom const char  xk[20];
rom const char  yk[20];
rom const char  xkklein[16];
rom const char  ykklein[16];
rom const char  xl[16];
rom const char  yl[16];
rom const char  xlklein[12];
rom const char  ylklein[12];
rom const char  xm[23];
rom const char  ym[23];
rom const char  xmklein[18];
rom const char  ymklein[18];
rom const char  xn[23];
rom const char  yn[23];
rom const char  xnklein[15];
rom const char  ynklein[15];
rom const char  xo[22];
rom const char  yo[22];
rom const char  xoklein[18];
rom const char  yoklein[18];
rom const char  xp[21];
rom const char  yp[21];
rom const char  xpklein[18];
rom const char  ypklein[18];
rom const char  xq[25];
rom const char  yq[25];
rom const char  xqklein[20];
rom const char  yqklein[20];
rom const char  xr[24];
rom const char  yr[24];
rom const char  xrklein[12];
rom const char  yrklein[12];
rom const char  xs[21];
rom const char  ys[21];
rom const char  xsklein[16];
rom const char  ysklein[16];
rom const char  xt[17];
rom const char  yt[17];
rom const char  xtklein[14];
rom const char  ytklein[14];
rom const char  xu[21];
rom const char  yu[21];
rom const char  xuklein[14];
rom const char  yuklein[14];
rom const char  xv[19];
rom const char  yv[19];
rom const char  xvklein[13];
rom const char  yvklein[13];
rom const char  xw[21];
rom const char  yw[21];
rom const char  xwklein[15];
rom const char  ywklein[15];
rom const char  xx[19];
rom const char  yx[19];
rom const char  xxklein[15];
rom const char  yxklein[15];
rom const char  xy[17];
rom const char  yy[17];
rom const char  xyklein[16];
rom const char  yyklein[16];
rom const char  xz[21];
rom const char  yz[21];
rom const char  xzklein[15];
rom const char  yzklein[15];
#endif /* __dingens */

#ifdef __is_PC
char  x0klein[25];
char  y0klein[25];
char  x1klein[15];
char  y1klein[15];
char  x2klein[20];
char  y2klein[20];
char  x3klein[19];
char  y3klein[19];
char  x4klein[20];
char  y4klein[20];
char  x5klein[22];
char  y5klein[22];
char  x6klein[23];
char  y6klein[23];
char  x7klein[17];
char  y7klein[17];
char  x8klein[23];
char  y8klein[23];
char  x9klein[23];
char  y9klein[23];
char  xa[22];
char  ya[22];
char  xaklein[20];
char  yaklein[20];
char  xaus[12];
char  yaus[12];
char  xb[26];
char  yb[26];
char  xbklein[21];
char  ybklein[21];
char  xc[19];
char  yc[19];
char  xcklein[17];
char  ycklein[17];
char  xd[24];
char  yd[24];
char  xdklein[21];
char  ydklein[21];
char  xe[21];
char  ye[21];
char  xeklein[19];
char  yeklein[19];
char  xf[18];
char  yf[18];
char  xfklein[15];
char  yfklein[15];
char  xfrag[16];
char  yfrag[16];
char  xg[23];
char  yg[23];
char  xgklein[23];
char  ygklein[23];
char  xh[23];
char  yh[23];
char  xhklein[18];
char  yhklein[18];
char  xi[17];
char  yi[17];
char  xiklein[11];
char  yiklein[11];
char  xj[17];
char  yj[17];
char  xjklein[12];
char  yjklein[12];
char  xk[20];
char  yk[20];
char  xkklein[16];
char  ykklein[16];
char  xl[16];
char  yl[16];
char  xlklein[12];
char  ylklein[12];
char  xm[23];
char  ym[23];
char  xmklein[18];
char  ymklein[18];
char  xn[23];
char  yn[23];
char  xnklein[15];
char  ynklein[15];
char  xo[22];
char  yo[22];
char  xoklein[18];
char  yoklein[18];
char  xp[21];
char  yp[21];
char  xpklein[18];
char  ypklein[18];
char  xq[25];
char  yq[25];
char  xqklein[20];
char  yqklein[20];
char  xr[24];
char  yr[24];
char  xrklein[12];
char  yrklein[12];
char  xs[21];
char  ys[21];
char  xsklein[16];
char  ysklein[16];
char  xt[17];
char  yt[17];
char  xtklein[14];
char  ytklein[14];
char  xu[21];
char  yu[21];
char  xuklein[14];
char  yuklein[14];
char  xv[19];
char  yv[19];
char  xvklein[13];
char  yvklein[13];
char  xw[21];
char  yw[21];
char  xwklein[15];
char  ywklein[15];
char  xx[19];
char  yx[19];
char  xxklein[15];
char  yxklein[15];
char  xy[17];
char  yy[17];
char  xyklein[16];
char  yyklein[16];
char  xz[21];
char  yz[21];
char  xzklein[15];
char  yzklein[15];

#endif /*__is_PC */
